language: node_js
cache:
  directories:
    - node_modules
script:
  - npm install -g knex bower
  - bower install
  - knex migrate:latest
  - npm test
after_success:
  - .travis/on_build_complete.sh "1"
after_failure:
  - .travis/on_build_complete.sh "0"
